name: Deploy Development
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (default: latest)"
        required: false
        default: latest
jobs:
  deploy-development:
    name: Deploy App (Development)
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEVELOPMENT_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
      - name: Add host to known_hosts
        run: |
          ssh-keyscan -t rsa,ed25519 ${{ vars.DEVELOPMENT_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Update .env on server
        run: |
          ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEVELOPMENT_HOST }} \
            "sed -i 's/^AUTO_GO_APP_VERSION=.*/AUTO_GO_APP_VERSION=${{ github.event.inputs.version }}/g' /opt/docker/.env"
      - name: Show updated .env
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEVELOPMENT_HOST }} cat /opt/docker/.env
      - name: Restart service via Docker Compose
        run: |
          ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEVELOPMENT_HOST }} \
            "cd /opt/docker/ && sudo docker compose up -d --force-recreate auto-go-app" || exit 0
