name: Build and Push to Docker Hub

on:
  push:
    branches: [main]
    tags: ["v*.*.*"] # Matches semantic version tags like v0.0.1
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: thienhaole92/auto-go-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine tags
        id: tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            version=${GITHUB_REF#refs/tags/v}
            echo "version_tag=$version" >> $GITHUB_OUTPUT
            echo "tags=$IMAGE_NAME:$version,$IMAGE_NAME:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=$IMAGE_NAME:latest" >> $GITHUB_OUTPUT
          fi
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
