name: Build and Push to Docker Hub

on:
  push:
    branches: [main]
    tags: ["v*.*.*"] # Matches semantic version tags like v0.0.1
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: thienhaole92/auto-go-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Determine tags
        id: tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            version=${GITHUB_REF#refs/tags/v}
            echo "::set-output name=version_tag::$version"
            echo "::set-output name=tags::$IMAGE_NAME:$version,$IMAGE_NAME:latest"
          else
            echo "::set-output name=tags::$IMAGE_NAME:latest"
          fi
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
